spring:
    application:
        name: zeta-runner
    rabbitmq:
        host: ${SPRING_RABBITMQ_HOST}
        port: ${SPRING_RABBITMQ_PORT}
        username: ${SPRING_RABBITMQ_USERNAME}
        password: ${SPRING_RABBITMQ_PASSWORD}
        queues:
            deployment: ${SPRING_RABBITMQ_QUEUES_DEPLOYMENT:zeta.deployments}
            delete: ${SPRING_RABBITMQ_QUEUES_DELETE:zeta.delete}

server:
    port: 8000

app:
    namespace: ${APP_NAMESPACE}
    image-engine:
        url: ${APP_IMAGE_ENGINE_URL}
    object-storage:
        serviceUrl: ${APP_OBJECT_STORAGE_SERVICEURL}
        username: ${APP_OBJECT_STORAGE_USERNAME}
        password: ${APP_OBJECT_STORAGE_PASSWORD}
        bucket: ${APP_OBJECT_STORAGE_BUCKET:zeta}
    registry:
        clusterIp: ${APP_REGISTRY_CLUSTERIP}
        port: ${APP_REGISTRY_PORT}
        serviceUrl: ${APP_REGISTRY_SERVICEURL}
    runner:
        version: ${APP_RUNNER_VERSION:-0.0.1}
        base-image: ${APP_RUNNER_BASE_IMAGE:-zeta-base-runner-python:0.0.1}
