FROM python:3.14
WORKDIR /zeta
COPY requirements.txt /requirements.txt
RUN pip install -r /requirements.txt
COPY handler /zeta/handler
COPY runner.py /zeta/runner.py
EXPOSE 80
CMD [ "fastapi", "run", "/zeta/runner.py", "--port", "80" ]