apiVersion: v1
kind: ConfigMap
metadata:
  name: zeta-runner-cm
  namespace: zeta
data:
  SPRING_RABBITMQ_HOST: "${SPRING_RABBITMQ_HOST}"
  SPRING_RABBITMQ_PORT: "${SPRING_RABBITMQ_PORT}"
  SPRING_RABBITMQ_USERNAME: "${SPRING_RABBITMQ_USERNAME}"
  SPRING_RABBITMQ_PASSWORD: "${SPRING_RABBITMQ_PASSWORD}"
  SPRING_RABBITMQ_QUEUES_DEPLOYMENT: "${SPRING_RABBITMQ_QUEUES_DEPLOYMENT}"
  SPRING_RABBITMQ_QUEUES_DELETE: "${SPRING_RABBITMQ_QUEUES_DELETE}"

  APP_NAMESPACE: "${APP_NAMESPACE}"

  APP_IMAGE_ENGINE_URL: "${APP_IMAGE_ENGINE_URL}"

  APP_OBJECT_STORAGE_SERVICEURL: "${APP_OBJECT_STORAGE_SERVICEURL}"
  APP_OBJECT_STORAGE_USERNAME: "${APP_OBJECT_STORAGE_USERNAME}"
  APP_OBJECT_STORAGE_PASSWORD: "${APP_OBJECT_STORAGE_PASSWORD}"
  APP_OBJECT_STORAGE_BUCKET: "${APP_OBJECT_STORAGE_BUCKET}"

  APP_REGISTRY_CLUSTERIP: "${APP_REGISTRY_CLUSTERIP}"
  APP_REGISTRY_PORT: "${APP_REGISTRY_PORT}"
  APP_REGISTRY_SERVICEURL: "${APP_REGISTRY_SERVICEURL}"

  APP_RUNNER_VERSION: "${APP_RUNNER_VERSION}"
  APP_RUNNER_BASE_IMAGE: "${APP_RUNNER_BASE_IMAGE}"