apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zeta-rb
  namespace: zeta
subjects:
  - kind: ServiceAccount
    name: zeta-sa
roleRef:
  kind: Role
  name: zeta-role
  apiGroup: rbac.authorization.k8s.io
