apiVersion: v1
kind: ConfigMap
metadata:
  name: zeta-apiserver-cm
  namespace: zeta
data:
  SPRING_RABBITMQ_HOST: "${SPRING_RABBITMQ_HOST}"
  SPRING_RABBITMQ_PORT: "${SPRING_RABBITMQ_PORT}"
  SPRING_RABBITMQ_USERNAME: "${SPRING_RABBITMQ_USERNAME}"
  SPRING_RABBITMQ_PASSWORD: "${SPRING_RABBITMQ_PASSWORD}"

  SPRING_RABBITMQ_QUEUES_DEPLOYMENT: "${SPRING_RABBITMQ_QUEUES_DEPLOYMENT}"
  SPRING_RABBITMQ_QUEUES_DELETE: "${SPRING_RABBITMQ_QUEUES_DELETE}"

  SPRING_DATASOURCE_URL: "${SPRING_DATASOURCE_URL}"
  SPRING_DATASOURCE_USERNAME: "${SPRING_DATASOURCE_USERNAME}"
  SPRING_DATASOURCE_PASSWORD: "${SPRING_DATASOURCE_PASSWORD}"

  APP_NAMESPACE: "${APP_NAMESPACE}"

  APP_OBJECT_STORAGE_SERVICEURL: "${APP_OBJECT_STORAGE_SERVICEURL}"
  APP_OBJECT_STORAGE_USERNAME: "${APP_OBJECT_STORAGE_USERNAME}"
  APP_OBJECT_STORAGE_PASSWORD: "${APP_OBJECT_STORAGE_PASSWORD}"
  APP_OBJECT_STORAGE_BUCKET: "${APP_OBJECT_STORAGE_BUCKET}"