apiVersion: v1
kind: Service
metadata:
  name: zeta-apiserver
  namespace: zeta
spec:
  selector:
    app: zeta-apiserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
  